export const LOAD_TOURNAMENTS_SUCCESS = 'LOAD_TOURNAMENTS_SUCCESS';
export const LOAD_TOURNAMENTS_FAIL = 'LOAD_TOURNAMENTS_FAIL';
export const EDIT_TOURNAMENT = 'EDIT_TOURNAMENT';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
export const CREATE_NEW_TOURNAMENT = 'CREATE_NEW_TOURNAMENT';
export const LOAD_FILTERED_TOURNAMENTS_SUCCESS =
  'LOAD_FILTERED_TOURNAMENTS_SUCCESS';
